[project]
authors = ["Josh S Wilkinson <joshswilkinson@pm.me>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "csv parser in mojo"
name = "mojo_csv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
