[project]
authors = ["Josh S Wilkinson <joshswilkinson@pm.me>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "csv parser in mojo"
name = "mojo_csv"
platforms = ["linux-64"]
version = "1.2.1"

[tasks]
test = "mojo test tests/mojo_csv"
test-dev = "mojo test_parse.mojo"
format = { cmd = "mojo format -l 88 ." }
prep = { depends-on = ["format", "test-dev"] }
bench = "mojo tests/bench.mojo"
pack = "mojo package src -o .pixi/envs/default/lib/mojo/mojo_csv.mojopkg;cp .pixi/envs/default/lib/mojo/mojo_csv.mojopkg dist;sha256sum dist/mojo_csv.mojopkg | awk -F ' ' '{print $1}' > dist/mojo_csv.mojopkg.sha256sum;"
test-build = { cmd = "rattler-build build --channel https://prefix.dev/modular-community --channel https://conda.modular.com/max --channel conda-forge --variant-config tests/variants.yaml --skip-existing=all --recipe tests/recipe.yaml", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }



[dependencies]
max = ">=25.1.0,<26"
#
